[project]
name = "primitive-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tanya13707", email = "tanyanyusha@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "prompt>=0.4.1",
]

[project.scripts]
project = "primitive_db.main:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 88
target-version = "py312"
exclude = ["venv", ".venv", "dist", "__pycache__"]

[tool.ruff.lint]
select = ["E", "F", "I"]
ignore = []

[dependency-groups]
dev = [
    "ruff>=0.16.10",
]
